export const workspaceCopy = {
  'zh-CN': {
    tagline: 'CONNECT · COLLABORATE · BUILD TOMORROW',
    logout: '退出',
    bench: '工作台',
    welcomeNav: '欢迎',
    wordNav: '文字生成',
    imageNav: '图片生成',
    settingsNav: '设置',
    welcomeTitle: '欢迎回来',
    welcomeHint: '选择一个能力，开始今天的创作。',
    wordHint: '用提示词快速生成文案、邮件和摘要。',
    imageHint: '描述画面，选择风格与比例，生成图片。',
    settingsHint: '管理账号、语言与外观。',
    open: '进入',
    wordTitle: '文字生成',
    wordSub: '输入提示词，生成文稿',
    wordPlaceholder: '请输入你想生成的内容...',
    typeCopy: '文案',
    typeMail: '邮件',
    typeSummary: '摘要',
    generate: '生成',
    generating: '生成中…',
    copy: '复制',
    copied: '已复制',
    resultEmpty: '生成结果会显示在这里',
    imageTitle: '图片生成',
    imagePlaceholder: '描述你想生成的图片…',
    styleReal: '写实',
    styleOil: '油画',
    styleIllust: '插画',
    generateImage: '生成图片',
    download: '下载',
    settingsTitle: '设置',
    account: '账号',
    nickname: '昵称',
    email: '邮箱',
    language: '语言',
    appearance: '外观',
    darkTheme: '深色主题',
    security: '安全',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    save: '保存设置',
    saved: '设置已保存（仅前端）',
    passwordMismatch: '两次输入的新密码不一致',
    passwordDemo: '密码修改仅为前端演示，尚未接入接口',
    notFound: '页面不存在',
    backHome: '返回欢迎页',
  },
  'en-US': {
    tagline: 'CONNECT · COLLABORATE · BUILD TOMORROW',
    logout: 'Log out',
    bench: 'Workspace',
    welcomeNav: 'Welcome',
    wordNav: 'Text',
    imageNav: 'Image',
    settingsNav: 'Settings',
    welcomeTitle: 'Welcome back',
    welcomeHint: 'Pick a tool and start creating.',
    wordHint: 'Turn a prompt into copy, email, or a summary.',
    imageHint: 'Describe a scene, pick style and ratio, generate images.',
    settingsHint: 'Manage account, language, and appearance.',
    open: 'Open',
    wordTitle: 'Text generation',
    wordSub: 'Write a prompt to generate a draft',
    wordPlaceholder: 'Describe what you want to generate…',
    typeCopy: 'Copy',
    typeMail: 'Email',
    typeSummary: 'Summary',
    generate: 'Generate',
    generating: 'Generating…',
    copy: 'Copy',
    copied: 'Copied',
    resultEmpty: 'Results will appear here',
    imageTitle: 'Image generation',
    imagePlaceholder: 'Describe the image you want…',
    styleReal: 'Realistic',
    styleOil: 'Oil painting',
    styleIllust: 'Illustration',
    generateImage: 'Generate images',
    download: 'Download',
    settingsTitle: 'Settings',
    account: 'Account',
    nickname: 'Nickname',
    email: 'Email',
    language: 'Language',
    appearance: 'Appearance',
    darkTheme: 'Dark theme',
    security: 'Security',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    save: 'Save settings',
    saved: 'Settings saved (frontend only)',
    passwordMismatch: 'New passwords do not match',
    passwordDemo: 'Password change is a frontend demo and is not connected yet',
    notFound: 'Page not found',
    backHome: 'Back to welcome',
  },
} as const
